### ISSUE TITLE
Rockman X4 background music gets stuck in a loop or "locks" on the same note

### ISSUE THREAD

**Issue by lordviceroy** [satiator/compatibility#10]
**What game is it?**

Title: Rockman X4

Region: JP

Serial: Unknown

**Where did you get the image?**

Redump

**Provide SHA1 hashes of the image file(s)**

eg. on Linux/Mac you can do this for files named `foo.bin`, `foo.cue` etc  by running `sha1sum foo.*`

```
C2CF36457262E9B62579C9FAB2FFB31F03D86599 track 1
59E97B923E5473DE495BF7F74F2DE15E39515969 track 2
0DE8A90F0514565F46ABD43D9F6D131E87FE1544 track 3
2409A32739593B75D398CA6C48D3320F3A762E41 cue file
```

**What is the behaviour you observe?**
Playing through the game eventually results in the background music getting stuck in a loop or "locking" on the same note. Think of it as if a game were to crash or lock up, and the music note at the point where the game crashes repeats at a rapid loop. Moving to a new part of the game where the music changes will fix the issue, but it will eventually get stuck again at some point. It's difficult to consistently repro this behavior at a specific point, it just seems to randomly happen. The skipping background music seems to have no impact on your ability to continue playing the game.

I have a suspicion this is the same bug as or related to Issue #9, as I am able to repro that and it's the exact same problem I am experiencing with X4.

- Where in the game?
Throughout, but seems to happen more consistently during the second "Intro" level with Zero.

- What triggers the behaviour?
Simply playing through the game eventually results in the background music getting stuck in a loop.

**What is the behaviour you expect?**
Playing through the game will not result in the background music getting stuck in a loop.

- Provide comparison to a real disc if possible
N/A

**Satiator Info**
- Firmware version
153

- Menu version
55

**Comment by joeldahl** [comment]
FWIW, the exact same thing happened yesterday while playing Bubble Symphony. The music gets stuck on a single note, happened after playing for 10 minutes or so. Firmware 153 and Menu 59.

**Comment by lordviceroy** [comment]
Video of the issue:
https://discordapp.com/channels/491170063869673482/745769134377140355/798632160420429824

**Comment by lordviceroy** [comment]
Another report of the same issue:
https://discord.com/channels/491170063869673482/745769134377140355/810408825059803186

**Comment by robertragno** [comment]
Wanted to add something I noticed when this occurred today on FW156 Menu64. Controller input polling rate seemed to be halved. When the glitching music occurs X wasn't able to shoot consistently at his normal rate of fire and it was as if about 1/2 the button inputs for fire were being dropped.

**Comment by imjustcalledtwobrothers** [comment]
> FWIW, the exact same thing happened yesterday while playing Bubble Symphony. The music gets stuck on a single note, happened after playing for 10 minutes or so. Firmware 153 and Menu 59.

I also experienced this while playing Bubble Symphony. I’d been playing for about 30 minutes before it occurred, so it’s probably not easy to consistently reproduce.

**Comment by andy83-projects** [comment]
same issue for Megaman X4

**Comment by lordviceroy** [comment]
Thanks for the info @andy83-projects. If you could let us know the MNU and FW version you're running, that would be helpful. You can check the bottom left of the menu screen for this information.

**Comment by andy83-projects** [comment]
Firmware 156 and menu 66.  The current from the latest.

also maybe to note.  When sound locks up as MEGAMAN on dragoons stage, the game will reset the system to the CD player after changing areas

**Comment by abrasive** [comment]
Does this still occur with FW 157 or newer?

**Comment by lordviceroy** [comment]
Played through the entire intro stage and the jungle stage as Zero on the MSHvSF-fixed FW and Menu 67, music never skipped. I think this can be closed as fixed @abrasive!
