### ISSUE TITLE
Audio glitches with all games

### ISSUE THREAD

**Issue by Rikroka** [satiator/compatibility#15]
I see this place is for specific game issues but I don't know where else to get support.

I'm using a Japanese Saturn, HST-3220. On all games I've tried with the Satiator every so often (once per 20-30 minutes or so) the audio will glitch, 1 or 2 seconds of stuttering/skipping. It doesn't happen with game CDs.

**Comment by lordviceroy** [comment]
Please join the Discord and ask in the #help channel:
https://discord.gg/xk6MNvACeV

Please use this template once you're in #help and somebody will jump in to assist:
https://discord.com/channels/491170063869673482/745769134377140355/806945538577530950

**Comment by lordviceroy** [comment]
@abrasive I think this one can be closed as won't fix/answered. Issue was addressed in Discord.
