### ISSUE TITLE
In The Hunt hangs while loading...

### ISSUE THREAD

**Issue by jcchaconjr** [satiator/compatibility#16]
**What game is it?**

Title: In the Hunt

Region: US

Serial: T-10001H

Archive.org Redump Sega Saturn page:
https://archive.org/details/RedumpSegaSaturn2019October17MIA1

In The Hunt (USA) (Track 01).bin - SHA1: FE1A957A99D2072D3DBEF30307A03DB731E196C6
In The Hunt (USA) (Track 02).bin - SHA1: B702089360F53DAB98FA1B7C66D4A184B94FC311
In The Hunt (USA) (Track 03).bin - SHA1: 0E08C50835D6D0F9CDF8B64DC92292169A1F627F
In The Hunt (USA) (Track 04).bin - SHA1: A67F3D4E530EDBB379FA9D17C298168EDD3ADEA4
In The Hunt (USA) (Track 05).bin - SHA1: 389BD1A9761F94B1AC645276FA3F0ABBA8DA583E
In The Hunt (USA) (Track 06).bin - SHA1: 189BABD3245FBEDC5E2FDA4C265E8471FE75A09B
In The Hunt (USA) (Track 07).bin - SHA1: 3CF13A6E0BB89F5360B2CFB3B5EF0AF1BB3B7DAA
In The Hunt (USA) (Track 08).bin - SHA1: F4CDD2010496C52EB311428549E56AB32E866854
In The Hunt (USA) (Track 09).bin - SHA1: 8C5401642832C10A94B5FC7BDBD7DC31BB9448F5
In The Hunt (USA) (Track 10).bin - SHA1: 87B61DFAA006DBD677A3DDB7FE3720246C274B24
In The Hunt (USA) (Track 11).bin - SHA1: 1F20FD2AB6A5E7BB3E3A42F520937B48DAA81D8A
In The Hunt (USA) (Track 12).bin - SHA1: 05F733BCA5EAA3DAAD0E808136D17673607A13B9
In The Hunt (USA) (Track 13).bin - SHA1: 8ECA553F99730A7AC89B70DC88B0FC0E2034A7D3
In The Hunt (USA).cue - SHA1: 1F8A5CD9D92B8CB339B45837F446F9B28F616D9B

(All CRC checks performed with 7-zip in Windows 10)

Symptoms:

The game will go to a black screen either immediately, or while the Kokopeli intro video is playing. I have heard that there is a workaround by leaving the controller disconnected until the title screen comes up, so I will try this and report.
**EDIT:** Yes, I confirmed that if I unplug the controller as soon as I select the game, It will load properly. Once past the Kokopeli intro video, you can plug in a controller and it will load up.

**UPDATE:** I tried Kaitei Daisensou (also taken from the Redump), and it doesn't have this problem. I also Googled this issue, and it appears to be an issue with a particular version of the game, which apparently is what's stored in this redump... SO if that's the case, I think this issue can be closed as a "real disc" problem... Now to find an image of the version that doesn't have this problem...

This is using an early Model 1 Saturn.

I don't have the real disc ATM, unfortunately.

**Comment by lordviceroy** [comment]
You're correct that this is a known issue with the original disc. Booting the game with no controllers plugged in is the correct workaround. Expected behavior, not a Satiator bug. :)

**Comment by jcchaconjr** [comment]
Agreed - closing...
