### ISSUE TITLE
Sakura Taisen (JPN) Hangs in Attract Mode (Random)

### ISSUE THREAD

**Issue by NixMcRetro** [satiator/compatibility#18]
**What game is it?**
Title: Sakura Taisen
Region: JPN

**Where did you get the image?**
Redump - Sakura Taisen (Japan) (Disc 1) (6M)

**Provide SHA1 hashes of the image file(s)**
```
083f24d691a7bd38f228bf5d2a5dfb7578df3a91  Sakura Taisen (Japan) (Disc 1) (6M).cue
76f3b13c6dc7429b1df475c68edfd9dc37feca27  Sakura Taisen (Japan) (Disc 1) (6M) (Track 1).bin
47bf9670935ec1310afb6870781b7ca9dbacd065  Sakura Taisen (Japan) (Disc 1) (6M) (Track 2).bin
```

**What is the behaviour you observe?**
- Hang during attract mode (FMV).
- Video freezes.
- Audio is in a short loop.
- Appears to be random in timing.

**What is the behaviour you expect?**
Burnt copy of disc shows no issues, loops on attract mode for 12+ hours. First noticed this with the fan translation so I tried with a non-patched version from Redump and it shows the same behaviour. If left running attract mode it will freeze within several hours.

**Firmware / Menu**
v157 / v64

**Hardware**
Model: HST-3220 VA15
Serial: B8F015896
Region: NTSC-J

**Comment by TrekkiesUnite118** [comment]
So I've had the first disc running the attract mode for about 5 hours now on my US Model 2 Saturn, VA6 revision with the Firmware 161 and Menu version 69. I haven't had any crashes yet. I also was able to fully complete the game from start to finish.

I think it's safe to say this is no longer an issue.
