### ISSUE TITLE
Jikkyu Oshaberi Parodius not starting

### ISSUE THREAD

**Issue by jlfernandezt** [satiator/compatibility#23]
Jikkyou Oshaberi Parodius - Forever with Me (Japan)

Title: Jikkyou Oshaberi Parodius - Forever with Me

Region: Japan

Serial: T-9513G

**Where did you get the image?**

Redump

**Provide SHA1 hashes of the image file(s)**

32cec306f73952da14147b9ae40fb8177b5d6e60  Jikkyou Oshaberi Parodius - Forever with Me (Japan) (Track 1).bin
21d50d70959dbfd8f2ddc422fd29b2c6e8f86ab1  Jikkyou Oshaberi Parodius - Forever with Me (Japan) (Track 2).bin
5afb8b6f40f5c9d4624bd9acfb4584de2a2cf30c  Jikkyou Oshaberi Parodius - Forever with Me (Japan) (Track 3).bin
bedc797e2bd62f37020d1b7f67ae3c8fb3c26493  Jikkyou Oshaberi Parodius - Forever with Me (Japan) (Track 4).bin
b227e20ab31390427270a3c52c789a28ef60d19c  Jikkyou Oshaberi Parodius - Forever with Me (Japan) (Track 5).bin
c0e876f446cc9f509e4e45c9463af9a3f93cfc16  Jikkyou Oshaberi Parodius - Forever with Me (Japan) (Track 6).bin
48b23eb1ef1112afeaf6ec966822665eafe79b8f  Jikkyou Oshaberi Parodius - Forever with Me (Japan) (Track 7).bin
732be01d2490e18d86b6a8faf5fdd31bf938bb91  Jikkyou Oshaberi Parodius - Forever with Me (Japan) (Track 8).bin
a4bcfd8e98ca4ad1f66caee78b3e5e9f9f596a8f  Jikkyou Oshaberi Parodius - Forever with Me (Japan).cue

**What is the behaviour you observe?**

- Where in the game? Black screen after SEGA logo.
- What triggers the behaviour? Starting the game. 

**What is the behaviour you expect?**

- Provide comparison to a real disc if possible
Original disc works (with Action Replay). After the SEGA logo it goes into the Konami screen. 
I have an HST-3220. I'm using an Action Reply. Satiator is on the latest firmware and menu. I'm using the Satiator Rings launcher but it doesn't work from either launcher.  SD Card is a 128GB Sandisk card.

**Comment by ncc1701p** [comment]
I have a IMG burned image and it boots for me on 157 firmware. 64Gb Sandisk Extreme.
PS K:\Jikkyou Oshaberi Parodius Forever With Me (JP)> Get-Filehash '.\Jikkyou Oshaberi Parodius Forever With Me (JP).img'

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          8FA956415C49DCAF5C87E82C433A090EA66FAD77791F0191AAA55AC8356D8B99       K:\Jikkyou Oshaberi Parodius ...


https://youtu.be/MMeQikl1Aho

**Comment by DerekPascarella** [comment]
I tested this out with the dump found on the "redump revival" repository on archive.org and it booted without issue.  Checksums differ from yours @jlfernandezt.

```
beadea1467eef8bf4c553c8f6bbdf9b8  Jikkyou Oshaberi Parodius - Forever with Me (Japan) (Track 1).bin
1129a45d483e86d78b41ce04234827df  Jikkyou Oshaberi Parodius - Forever with Me (Japan) (Track 2).bin
48ab3c479eb03fb432fe38f9eaa7e87c  Jikkyou Oshaberi Parodius - Forever with Me (Japan) (Track 3).bin
723b9f75c79f9a60f9d6b4f2876f9dc1  Jikkyou Oshaberi Parodius - Forever with Me (Japan) (Track 4).bin
1282063e86e012d0df5ed358b100cf19  Jikkyou Oshaberi Parodius - Forever with Me (Japan) (Track 5).bin
a842a5c7537348f1246f02e6ec89993c  Jikkyou Oshaberi Parodius - Forever with Me (Japan) (Track 6).bin
912b15950ec274637e69503d7143503d  Jikkyou Oshaberi Parodius - Forever with Me (Japan) (Track 7).bin
90ca9a0d8105e1796e93dda511537ab3  Jikkyou Oshaberi Parodius - Forever with Me (Japan) (Track 8).bin
736692566f048847d8b6167614a9171f  Jikkyou Oshaberi Parodius - Forever with Me (Japan).cue
```

**EDIT:** I accidentally provided MD5s, please disregard.  Game still works, though.

**Comment by lordviceroy** [comment]
Works fine for me, I seem to have the same hash as jlfernandezt. Also using Redump image.

```
Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA1            32CEC306F73952DA14147B9AE40FB8177B5D6E60
SHA1            21D50D70959DBFD8F2DDC422FD29B2C6E8F86AB1
SHA1            5AFB8B6F40F5C9D4624BD9ACFB4584DE2A2CF30C
SHA1            BEDC797E2BD62F37020D1B7F67AE3C8FB3C26493
SHA1            B227E20AB31390427270A3C52C789A28EF60D19C
SHA1            C0E876F446CC9F509E4E45C9463AF9A3F93CFC16
SHA1            48B23EB1EF1112AFEAF6EC966822665EAFE79B8F
SHA1            732BE01D2490E18D86B6A8FAF5FDD31BF938BB91
SHA1            A4BCFD8E98CA4AD1F66CAEE78B3E5E9F9F596A8F
```

FW 157 MNU 66
1.01 System BIOS
400GB SanDisk Ultra SDXC Red+Grey
FAT32, 64KB Block Size
No cartridge in slot

**Comment by abrasive** [comment]
I can't reproduce this. Does it work without the AR?
