### ISSUE TITLE
FW 158 Music issues

### ISSUE THREAD

**Issue by xxx256** [satiator/compatibility#25]
At least a dozen NTSC-J games including Cyberbots are having music issues with FW 158. Usually the music stops completely after a few minutes into the various games. This issue wasn't present in FW 157. Also Asuka 120% freezes completely during the FMV intro.

**Comment by abrasive** [comment]
I'm aware of this, working on a fix now! Thanks for the report

**Comment by abrasive** [comment]
I'm having serious trouble reproducing this with any of the Satiators, Saturns and SD cards in my possession. I think it might be linked to card behaviour. Are you able to reproduce this with a different make/model of card?

**Comment by xxx256** [comment]
Ok. Here we go. NTSC-J V Saturn (model 1). Bios Ver. 1.01 & Samsung 64 PRO Plus / ExFat SD card.

-Cyberbots NTSC-J: Music drops 15 minutes into Devilottes Arcade story mode. Sound effects are still playing fine.

-SEGA Rally Plus NTSC-J: After 15 minutes Music drops. (on Mountain stage). Sound effects are still playing fine.

-Asuka 120% NTSC-J: Music stops after 15 minutes on the attract loop. Sound effects are still playing fine.

-Toshinden S NTSC-J: Music stops around 13 minutes into the 1P arcade mode. Sound effects are still playing fine.

-Capcom Generation 1 NTSC-J: 1943 Music hangs on the result screen. Then oddly resumes playing on the next stage. 

-Virtua Fighter REMIX NTSC-J: After 15 Minutes this game drops the Music as well.


Firmware 158 used / Menu 66. None of these audio issues were present in FW 157. All of the above issues also occur with a Samsung 32 PRO Micro SD card / ExFat.

**Comment by abrasive** [comment]
Thanks muchly for the detailed report. Thanks to your help I've finally been able to reproduce the issue - but only with the official release built on my CI system, not on the debug build from CI nor the release build on my workstation!

I had to rebuild the CI toolchain recently and 158 is the first built with the new one. Investigating now.

**Comment by thanius** [comment]
I can confirm this happening on Die Hard Arcade as well, using same firmware and around the 15 min mark. However, the music restarts after a couple of seconds of silence. Using SanDisk memory card.

**Comment by abrasive** [comment]
OK, I think I've got it. Can you try out this release candidate please?

[satiatorrc159-1.zip](https://github.com/satiator/compatibility/files/8320613/satiatorrc159-1.zip)

**Comment by xxx256** [comment]
Sure. Getting back to you in a bit.

**Comment by xxx256** [comment]
Works great. All the above music issues are fixed. This even fixed the Sega Rally replay narrator, who would glitch a lot in previous firmwares. Nice one!

**Comment by thanius** [comment]
Fixes for me too, even the Konami intro on Akumajo Dracula X which was having trouble playing for me. I do notice a hiccup where it previously stopped playing but the CDDA at least doesn't stop. It could be down to my card of course. Either way, great work!

**Comment by thanius** [comment]
Previously wrote I was using SanDisk but forgot that I upgraded to a 128GB Kingston a while ago

**Comment by abrasive** [comment]
Fixed in FW 159, available https://info.satiator.net/firmware
