### ISSUE TITLE
Issue with FW160 and rings menu

### ISSUE THREAD

**Issue by klandrith** [satiator/compatibility#33]
Upgraded to satiator FW160 and now satiator rings won't load. Don't know if this is a satiator or rings issue.

**Comment by privateye** [comment]
Satiator Rings v5.5 loads fine for me on FW160, and games will boot as long as `Auto Region Patch` is set to `On` (not `Off` or `Emu`). This setting is accessible by pressing Start in the games menu and then selecting `Options`.

**Comment by klandrith** [comment]
Thank you for the confirmation. I will try it again.

**Comment by klandrith** [comment]
Working fine other than issue with not being able to load original satiator menu from inside rings. I have no idea what the initial issue was.

**Comment by lordviceroy** [comment]
For issues with RINGS, it's recommended to check in the #rings-menu room on the Satiator Discord, It's a third-party menu and Abrasive does not provide technical support for it.

Glad the issue seems to be (mostly) resolved!
