### ISSUE TITLE
Could not find menu.bin

### ISSUE THREAD

**Issue by gingetheninj** [satiator/compatibility#36]
Every time I load up my Satiator it is saying could not find menu.bin on the SD card. 
I have tried 3 different SD cards and it still does not work at all. 
I have tried the the troubleshooting guide on the website and still does not seem to work.

**Comment by lordviceroy** [comment]
You may want to email info@satiator.net if you haven't already. Usually using the [SD Card Formatter](https://www.sdcard.org/downloads/formatter/) application and unzipping both menu.bin AND firmware.bin in the ROOT of the SD card resolves this issue.

cc @abrasive for awareness.

**Comment by gingetheninj** [comment]
Hi,

Thanks for you email it’s really appreciated I managed to sort by back tracking on the .bin menu and updating the latest firmware.

The item is working fine again and I can enjoy playing the games on it. :)

Paul Blanche

On 26 Jul 2023, at 15:04, lordviceroy ***@***.***> wrote:

﻿

You may want to email ***@***.******@***.***> if you haven't already. Usually using the SD Card Formatter<https://www.sdcard.org/downloads/formatter/> application and unzipping both menu.bin AND firmware.bin in the ROOT of the SD card resolves this issue.

cc @abrasive<https://github.com/abrasive> for awareness.
