### ISSUE TITLE
Panzer Dragoon Saga (USA) (Disc 1) (Redump)

### ISSUE THREAD

**Issue by EmeraldNova** [satiator/compatibility#5]
**What game is it?**

Title: Panzer Dragoon Saga (USA) (Disc 1)

Region: US

Serial: 81307

**Where did you get the image?**

Redump

**Provide SHA1 hashes of the image file(s)**
```
Panzer Dragoon Saga (USA) (Disc 1) (Track 1).bin
bd dd 53 e1 87 7e 73 3b 01 17 a7 9b a8 11 a4 70 1a c2 e4 1d

Panzer Dragoon Saga (USA) (Disc 1) (Track 2).bin
48 b2 9b 2a c0 5f 65 4e f7 18 cd 67 fd d2 53 8f 39 1c 52 9f

Panzer Dragoon Saga (USA) (Disc 1) (Track 3).bin
22 d7 1b 22 0d 24 ed ad c3 d6 0c fa fa 91 1d a1 4e 78 fc 85

Panzer Dragoon Saga (USA) (Disc 1).cue
93 e8 9a 90 69 d9 d0 d4 e1 9d 8d e6 cd 78 8f f1 01 2e 19 ec
```

**What is the behaviour you observe?**

FMV Cutscenes audio stutter

**What is the behaviour you expect?**

Smooth playback

**Comment by abrasive** [comment]
@EmeraldNova Is this still current since the main stutter fix landed?

**Comment by lordviceroy** [comment]
@abrasive A bunch of us tested this in #help channel on Discord last night; consensus seems to be that it works fine, and the people having issues at this point have slow SD cards or cluster sizes are too small (or both).

**Comment by missionrathe** [comment]
I’ve been playing on usa version no issues with fmv sounds in  first few hours.

**Comment by lordviceroy** [comment]
@abrasive I think this can be closed as fixed. Thanks!
