### ISSUE TITLE
Gex (USA) hangs at various points

### ISSUE THREAD

**Issue by abrasive** [satiator/compatibility#6]
**What game is it?**

Title: Gex

Region: USA

**Where did you get the image?**

Redump

**What is the behaviour you observe?**

Hangs are sometimes observed:

- when skipping the intro FMV, and
- at some points loading level or after dying.

The latter can be reproduced reliably using password TXZFKHGP and entering the level at lower left.
Sometimes this hangs at the level title screen, at different points in the animation.

**Comment by abrasive** [comment]
Reported by Radracer (Discord), brought to my attention by @EmeraldNova

**Comment by ferraca** [comment]
Hi! It is working fine to me using the last beta version (same that fix MvsSF). If more info is required, I can check to provide. I booted the game using Rings menu.

**Comment by privateye** [comment]
Unable to reproduce this issue in the Redump disc image (NTSC-U) with menu 67 and the latest test firmware (satiatormshvsf-0).

**Comment by abrasive** [comment]
Fixed in fw 160
