### ISSUE TITLE
Street Fighter Alpha 2 Gold and Street Fighter Zero 3 music issues

### ISSUE THREAD

**Issue by GerryHolt** [satiator/compatibility#9]
What game is it?

Street Fighter Collection (Alpha 2 Gold Disc) and Street Fighter Zero 3

Region: US for Alpha 2 and JP for Zero 3

Serial: 

Collection Disc 2
T-1222H

Zero 3
T-1246G

Where did you get the image?

Redump

Provide SHA1 hashes of the image file(s)

Street Fighter Collection Disc 2
SHA1 hash of Street Fighter Collection (USA) (Disc 2) (Track 1).bin:
47ccb411464bd53bf5c180e91ede3656cba68114
SHA1 hash of Street Fighter Collection (USA) (Disc 2) (Track 2).bin:
8dd55f9ba1f7cec180af8f3a05d8b96723e2561e
SHA1 hash of Street Fighter Collection (USA) (Disc 2).cue:
a142fab287322315b754acebf162b170cc21db2d

Street Fighter Zero 3
SHA1 hash of Street Fighter Zero 3 (Japan) (Track 1).bin:
b1cc45650b526ed88a82efcd315ee73e89a658d1
SHA1 hash of Street Fighter Zero 3 (Japan) (Track 2).bin:
eb8a96c9bd1358cc8606e099bad61762df07790a
SHA1 hash of Street Fighter Zero 3 (Japan).cue:
8136b0909951c3eb952ec846ae2b6005604c9c10

What is the behavior you observe?

It seems in both these games music can randomly cut out or get stuck repeating the same split second over and over until the song changes. I haven't been able to pin down what causes it as sometimes the track that was acting up will have worked without issue before. Changing songs often (say playing a stage, then getting a game over and letting the intro from A2Gold play seems to cause the music to cut out). I've only noticed this issue on these two games. I've not run into it yet on other games.

What is the behavior you expect?

Smooth playback

**Comment by BlackMajic** [comment]
The easiest way I've found to reproduce in SFZ3 is to play in _World Tour_ mode until unlocking the USSR stage. After beating R. Mika, I find the music will more often than not cut out whilst fighting Zangief.

[SFZERO3_001.txt (rename .BUP)](https://github.com/satiator/compatibility/files/6014245/SFZERO3_001.txt)

Loading the save proved less reliable, but I found swapping levels after an attempt helped reproduce (possibly on other levels.)

**Comment by stwalczyk** [comment]
I played Street Fighter Zero 2 Dash tonight with a friend on Versus and music would cut out during fighting rather consistently, more than 50% of the time. It even cut out in the menu once.

**Comment by abrasive** [comment]
Does this still occur with FW 157, released this week?

**Comment by stwalczyk** [comment]
It was on FW 156, but I will test it on FW 157 later today.

**Comment by BlackMajic** [comment]
Gave 157 a shot tonight, I didn't experience the music cut out in SFZ3 during my ~45m playtime. (had a pop, but probably unrelated)
I'll try to give it some more time later this week.

(I also had some stutter during the dracula x opening crawl that looks fixed also)

**Comment by stwalczyk** [comment]
> Does this still occur with FW 157, released this week?

After multiple hours in two player SFA2 and SFA3 we haven't experienced any sound cutting out. I wanted to make doubly sure that it wasn't related to two player mode so it took time to test.

Aside, I've noticed that resetting the console with the 4mb cartridge in causes the satiator to get ignored so the CD menu pops up. Maybe those need to be flashed in a way similar to the AR carts? I wasn't sure if I should make a ticket or not for that.
